spring:
   http:
      encoding:
      force: true
      charset: UTF-8
   datasource:
      member:
         ##这里如果是多数据源，需要使用 jdbc-url
         url: jdbc:mysql://localhost:3306/springboot_member?serverTimezone=GMT&characterEncoding=UTF-8
         username: root
         password: Qingliu987
         borrowConnectionTimeout: 30
         loginTimeout: 30
         maintenanceInterval: 60
         maxIdleTime: 60
         maxLifeTime: 20000
         maxPoolSize: 25
         minPoolSize: 3
         uniqueResourceName: memberDatasource
         ##driver-class-name: com.mysql.cj.jdbc.Driver
      order:
         url: jdbc:mysql://localhost:3306/springboot_order?serverTimezone=GMT&characterEncoding=UTF-8
         username: root
         password: Qingliu987
         borrowConnectionTimeout: 30
         loginTimeout: 30
         maintenanceInterval: 60
         maxIdleTime: 60
         maxLifeTime: 20000
         maxPoolSize: 25
         minPoolSize: 3
         uniqueResourceName: orderDatasource
         ##driver-class-name: com.mysql.cj.jdbc.Driver
   freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html; charset=utf-8
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      ##模板文件结尾
      suffix: .ftlh
      ##模板文件目录
      template-loader-path: classpath:/templates
